[build]
  base = "frontend"
  publish = "public"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https: wss: data:; img-src 'self' https: data:; font-src 'self' https: data:;"

[[headers]]
  for = "/src/scripts/*"
    [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/src/styles/*"
    [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
    [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8" 